spring.application.name=Smart Expense Tracker
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-calm-king-a859xcmu-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_gOYmPsuzc9U6
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

app.URL=http://localhost:8080/

# Email configuration (update with your SMTP credentials)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nutzycraft@gmail.com
spring.mail.password=vttk bqmj txun qbiu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true